name: Build and Test Inventrix App

on:
  push:
    branches:
      - main  # Space added after '-'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Build with Maven
        run: mvn clean package
